version: '3'
services:
  php:
    container_name: php
    build: php/.
    ports: 
      - "8000:8000"
    links: 
      - "mariadb:YT"
    volumes:
      -  ${PWD}/project/you-travel/www:/var/web
  mariadb:
    container_name: mariadb
    image: "mariadb:10.1"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    
  
